<div class="form-section">
    <form action="dashboard.php?page=add-farmer" method="post">
        <label for="names">Farmer's Name:</label>
        <input type="text" id="names" name="names" placeholder="e.g., omuntu omuntu" required>

        <label for="phone_number">Phone Number:</label>
        <input type="text" id="phone_number" name="phone_number" placeholder="e.g.,every number must start with 256 eg 256772123456" required>

        <label for="language">Preferred Language:</label>
        <select id="language" name="language">
            <option value="en">English</option>
            <option value="ruk">Rukiga</option>
        </select>

        <button type="submit" name="add_farmer">Add Farmer</button>
    </form>
</div>